identifier: kdzb90v3n475gc54
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: D:\test\my-blog
distFolder: dist/my-blog
outDir: D:\test\my-blog\dist\static
handle404: ''
allowErrorCollect: true
